title: Tech and Cloud musings - hosted with ❤️ with GitHub pages 
author: Sayan Ghosh
email: spammars@imnottellingu.com
description: > # this means to ignore newlines until "baseurl:"
  Azure, Cloud and technical stuff - let's get on with it!
theme: minima

# social links
twitter_username: sayanghosh # DO NOT include the @ character, or else the build will fail!
github_username:  sayanghosh123 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
